---
title: "Untitled"
format: html
editor: visual
---


```{r}
library(tidyverse)
library(janitor)
library(purrr)
```

You can add options to executable code like this

```{r}
soilresp <- read_csv("../data/soilresp_20240130.csv",
                    skip = 1, 
                    col_names = T,
                    trim_ws = T)
soilresp
```

```{r - data wrangling}
soilresp_w <- soilresp[-1,] %>% 
  clean_names() %>% 
  mutate(fco2_dry = as.numeric(fco2_dry)) %>% 
  mutate(swc_2_mean= as.numeric(swc_2_mean)) %>% 
  mutate(ts_2_mean=as.numeric(ts_2_mean)) %>% 
  mutate(label = as.numeric(label))
  
soilresp_mean <- soilresp_w %>% 
  group_by(label) %>% 
  summarise(mean_wc = mean(swc_2_mean,na.rm = T),
            mean_ts = mean(ts_2_mean,na.rm = T),
            mean_co2 = mean(fco2_dry)
    ) %>% 
  as.data.frame() %>% 
write_csv("../output/mean_flux20240130.csv")
  
  

```

```{r function}
soilresp_avg <- function(data, label, parameter){
  soilresp_avg %>% 
    group_by(label) %>% 
    nest() %>% 
    mutate(mean = map(data,
                      ))
    
    df
}

soilresp_avg(soilresp_w,label, parameter)
```

